name: Create Pull Request on Push to Publish

on:
  push:
    branches:
      - publish

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for existing PR
        id: check-pr
        run: |
          gh pr list --base main --head publish --json number --jq '. | length'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.check-pr.outputs.count == '0'
        run: gh pr create -B main -H publish --title 'Merge publish into main' --body 'Created by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
