name: Create Pull Request on Push to Publish

on:
  push:
    branches:
      - publish

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: gh pr create -B main -H publish --title 'Merge publish into main' --body 'Created by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
